app:
  bucketName: mytestbucketfors3messagestosqs41628192
  keyValue: test.txt
  columnValue: 1
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      accessKey:
      secretKey: 
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/182703514858/test-message-delivery
server:
  port: 9000
